name: jaguar_serializer
version: 2.2.13
description: Platform and format agnostic serializer built using source_gen
authors:
- Hugo van Galen <hugovangalen@gmail.com>
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_serializer

environment:
  sdk: '>=2.13.0-0 <3.0.0'

dev_dependencies:
  analyzer: ^1.7.0
  build_runner: ^2.0.4
  jaguar_serializer_cli:
    path: ../serializer_cli
